176375556 add is published logic
alissaVrk/lonely-mnt pull request #16
Opened 2021-01-12 12:47 UTC by EyalMecilati

2021-01-12 14:00 UTC, alissaVrk requested changes

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +    } else {
you don't need that

2021-01-12 14:00 UTC, alissaVrk commented on src/index.css
> +.toggleIsPublished {
use ant attributes please
easier to customize later

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +export default function validateIsPublished(company: any) {
naming - should be validate published company or something

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +      dispatch({
no reason to save on toggle change, we are lazy

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +        companyMainProjectId: editedCompany?.companyMainProjectId,
in general (though all of this can be deleted)
 you could have just passed edited company

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +      } else {
what about the error message to the user?

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +          {editedCompany ? (
you can show it anyway

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +                checked={
checked={!!editedCompany.isPublished}

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +            <div className="toggleIsPublished">
do we need all that?

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +const techPropertys = [
techProperties

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    for (let tech of project.techs.items) {
tech and deposit are part of project

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    return setReturn("each project should have 1 tech");
why don't you use it everywhere?

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    //check if each project have at least one techs
no reason for these comments, the error message is an explanation

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    if (deposite[type] && deposite[type].quantityType) {
what does  deposite[type].quantityType test?

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +export default function validateIsPublished(company: any) {
you can use types - Partial<Company> and such
I was lazy, just cause i didn't go through fields

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +  if (!result.success) {
you don't need this (the if)

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +  it("should works", () => {
move to top

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +  it("should fail when project dont have 1 tech", () => {
duplicate - change name

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +  it("should fail when tech dont have all required field", () => {
suggestion - put this in for loop over required fields

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +  });
add a test passing when indicated (for example) is null

2021-01-12 14:00 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +const testCompany = {
extract the test company to a different file please

2021-01-13 07:42 UTC, EyalMecilati commented on src/comps/forms/companyForm.tsx
> +      dispatch({
didn't quite get what is wrong and what to fix

2021-01-13 07:45 UTC, EyalMecilati commented on src/comps/forms/companyForm.tsx
> +          {editedCompany ? (
but it will mean nothing without a company to change its status, just like all the other features like projects and technical reports!?

2021-01-13 08:00 UTC, EyalMecilati commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    if (deposite[type] && deposite[type].quantityType) {
check if depositie.measured have quantityType if it does check for quantities. that what I understood from the instructions 
each deposit: if quantityType entry present should have at least one quantity

2021-01-13 08:14 UTC, EyalMecilati commented on src/comps/forms/helpers/validateIsPublished.tsx
> +  if (!result.success) {
if I don't have it the loop keeps ongoing since the return only jumps back one step. (that's what I find after many tries, could be wrong)

2021-01-14 07:57 UTC, alissaVrk requested changes

2021-01-14 07:57 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +      let checkCompanyIsValid = validatePublishedCompany(editedCompany);
please add a test showing why this doesn't work :)

2021-01-14 09:58 UTC, alissaVrk commented on cypress/integration/app/companyForm.spec.js
> +    Cypress.LocalStorage.clear = function (keys, ls, rs) {};
there is a function for that.. and it was used here

2021-01-14 10:01 UTC, alissaVrk commented on cypress/integration/app/companyForm.spec.js
> +  it("should try and fail to add company with isPublished set to true", () => {
you can't leave a failing test :)
it is possible to create a test that expects an error

2021-01-14 10:03 UTC, alissaVrk commented on cypress/utils/utils.js
> +        case INPUT_TYPES.SWITCH:
I'd change the name to something more generic, so it would include checkboxes and radio buttons as well

2021-01-14 10:06 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +      let validObj = editedCompany
you can just do {... editedCompany || {}, ...values}
by the way you need to use the values and not the params

2021-01-14 10:06 UTC, alissaVrk commented on cypress/integration/app/companyForm.spec.js
> +  //1. form - isPublished = true -> suceeds to save it
still missing

2021-01-14 10:07 UTC, alissaVrk requested changes
there are some comments :)
but all in all, great work :)

2021-01-14 12:34 UTC, alissaVrk requested changes
still missing the test

2021-01-14 12:34 UTC, alissaVrk commented on cypress/integration/app/companyForm.spec.js
> +  it.only("should update updates a company with options and warrents", () => {
remove only

2021-01-14 12:34 UTC, alissaVrk commented on cypress/integration/app/companyForm.spec.js
> +          fields: getWarrentsFields({ one: 0, two: 0 }),
why..?

2021-01-14 12:34 UTC, alissaVrk commented on cypress/utils/utils.js
> +  CONTROLLERS: { switch: "switch", checkbox: "checkbox", radio: "radio" },
no need for all of that, we talked about it

2021-01-14 12:34 UTC, alissaVrk commented on cypress/utils/utils.js
> +        case INPUT_TYPES.CONTROLLERS.switch:
and that :)

2021-01-17 07:52 UTC, alissaVrk commented on cypress/integration/app/isPublished.spec.js
> +  it.only("should add all fiealds to company with and check if ispublished is set to true", () => {
remove only

2021-01-17 07:52 UTC, alissaVrk commented on cypress/integration/app/isPublished.spec.js
> +        }
to make it shorter and to the point it would be nice to remove some fields..

2021-01-17 09:19 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +const techPropertys = [
..

2021-01-17 09:19 UTC, alissaVrk approved these changes

2021-01-17 09:20 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +export default function validateIsPublished(company: any) {
...

2021-01-17 09:21 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    for (let tech of project.techs.items) {
...

2021-01-17 17:54 UTC, alissaVrk requested changes

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +let errorArray: any = [];
please add a type..

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +    setReturn("you have to pass a company to be check for validity");
you can return here, it will make the code simpler

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
>  const setReturn = (errorMsg: string) => {
please rename to something that describe what it does

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
>  export default function validatePublishedCompany(company: any | null) {
you can use Partial type here, if you're not sure how - talk to me

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +  if (errorArray.length > 0) {
it isn't nice to return an array or an object..

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> -    success: false,
why do you need success: false in the array?

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +  if (project.techs.items !== 0) {
> 0 is nicer :)
besides you are missing the length.. - please add a test that will fail here
this will always return true

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +  if (project.deposits.items !== 0) {
same..

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
> +              "if " +
you can use \`  \` to create the string

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.tsx
>  import { QuantityType } from "../../../logic/graphAPI";
please rename to .ts

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +    expect(result[0].success).toBe(true);
insert these 2 lines in to a function, it will make these changes faster

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +      "should fail when " +
why do you skip the inferred here?

2021-01-17 17:54 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +      }
please add tests for the validation passing when there is no tech and/or no deposits (they will fail with your current code)

please add a test checking that you actually accumulate errors

2021-01-20 08:54 UTC, alissaVrk requested changes
good work :)
I didn't run the code an look at it

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +          errorMsgInfo(errorMsg);
does it look ok when you have multiple errors?

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +        let suggestion: any = confirmBeforePublish(validObj);
real type

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +        if (suggestion) {
please add a cypress test checking that you publish the company only if the users confirms the suggestions

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/publishedModal.tsx
> +  dispatch: (action: ActionForCompany) => Promise<unknown>;
types

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/publishedModal.tsx
> +    dispatch({
I think it would be better to not save until confirmation, cause you might end up with a temporary published company..
and I think it is better design to let the company form to deal with the dispatch and changing it's own state
anyway please add a cypress test for this

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/isPublished.test.ts
> +  it("should fail when project don't have tech and no deposits", () => {
it should pass..

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +let errorArray: string[] = [];
it can be const

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +  } else {
don't need else after return

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +    if ((company.projects?.items?.length || -1) === 0) {
-1 here is a problem..

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +    if ((company.projects?.items?.length || 0) > 0) {
btw, lodash has an `isEmpty` funtion to solve this || 0 thingy

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +  } else {
don't need else after return

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +          if ((deposite![type]!.quantities?.items?.length || -1) === 0) {
-1 no good..

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.test.ts
> +  it("should fail when project have tech report but not mineType", () => {
add a tests that passes if there is no tech and no mineType for example

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +export default function confirmBeforePublish(company: any) {
type

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +let errorArray: string[] = [];
...? why outside
remind me to explain why it's bad

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +  if (!company.options) {
use isEmpty, it could be an empty array (test)

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +    if (!project.ownership) {
like before, why no separate to a different function

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +      if (!project.mineName) {
duplicate :)

2021-01-20 08:54 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +import { techShouldHaveProperty } from "./testCompany";
importing from the testCompany here is weird..

2021-01-20 08:58 UTC, EyalMecilati commented on src/comps/forms/companyForm.tsx
> +          errorMsgInfo(errorMsg);
yes

2021-01-20 12:56 UTC, EyalMecilati commented on src/comps/forms/helpers/validateIsPublished.ts
> +let errorArray: string[] = [];
why? it's changing!

2021-01-20 12:58 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +let errorArray: string[] = [];
you push into the array, the array itself isn't changing

2021-01-20 13:03 UTC, EyalMecilati commented on src/comps/forms/helpers/validateIsPublished.ts
> +  } else {
its fail if not

2021-01-20 13:04 UTC, alissaVrk commented on src/comps/forms/helpers/validateIsPublished.ts
> +  } else {
....?

2021-01-20 13:26 UTC, EyalMecilati commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +      if (!project.mineName) {
what do you mean?

2021-01-20 13:32 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +      if (!project.mineName) {
oops, sorry :)

2021-01-20 13:35 UTC, EyalMecilati commented on src/comps/forms/helpers/validateIsPublished.ts
> +let errorArray: string[] = [];
cool

2021-01-21 08:10 UTC, alissaVrk requested changes
lets talk about the cypress test

2021-01-21 08:10 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +        let suggestion: string[] | null = confirmBeforePublish(validObj);
why let?

2021-01-21 08:10 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +      let validObj = { ...(editedCompany || {}), ...values };
why let?

2021-01-21 08:10 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.test.ts
> +describe("validation for isPublished", () => {
what about testing should pass..?
-with all things
-with no tech

2021-01-21 08:10 UTC, alissaVrk commented on src/comps/forms/helpers/confirmBeforePublish.ts
> +  const techShouldHaveProperty: Array<keyof Partial<ProjectTech>> = [
you don't need the `partial` here

2021-01-21 08:18 UTC, EyalMecilati commented on src/comps/forms/companyForm.tsx
> +  const [suggestionArray, setSuggestionArray] = useState(stringArr);
then how can i make the type of that state a string array ?

2021-01-21 08:36 UTC, alissaVrk commented on cypress/integration/app/isPublished.spec.js
> +  cy.get("#companySubmit").click();
please validate that `isPublished: false`

2021-01-21 12:11 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +  const [suggestionArray, setSuggestionArray] = useState(stringArr);
mmm try `[] as string[]`
not sure if this works

2021-01-21 13:57 UTC, EyalMecilati commented on src/comps/forms/companyForm.tsx
> +  const [suggestionArray, setSuggestionArray] = useState(stringArr);
works!

2021-01-21 17:50 UTC, alissaVrk submitted a review, later dismissed
1 comment :)

2021-01-21 17:50 UTC, alissaVrk commented on src/comps/forms/companyForm.tsx
> +  const setValuesFromCompanyForm = (params: any) => {
getValues.. (not set)

2021-01-29 04:48 UTC, alissaVrk approved these changes

2021-01-29 04:56 UTC, merged