Comparison page
alissaVrk/lonely-mnt pull request #22
Opened 2021-02-07 11:04 UTC by EyalMecilati

2021-02-08 10:03 UTC, alissaVrk commented on src/comps/Home.tsx
> +        <br />
my merge mistake..

2021-02-17 09:50 UTC, alissaVrk requested changes

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +  handleCompanyCheckBox: any;
any..?
rename to `onChangeCompanySelection` or something

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/CombineGraphs.tsx
> +          <div id={`${graph.param.field}_bars_graph`} className="barGraph">
why do you add a className?

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +            (selectedCompany) => selectedCompany.name !== company.name
better to compare ids, they have to be unique

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +            title: formValues.fieldOne,
should be the string to display to the user (from json)

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +            title: formValues.fieldOne,
in the tests, please use fields where there is a difference

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +      default:
it is wrong to assume that this is the default :)
there are 3 options, no default, if you want/need the default it should throw an error

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +    switch (formValues.graphCheckbox) {
I would convert both fields to  {field, param, format} outside the switch
and inside only assign them to the right places - less copy paste

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +        style={{
please don't style this way
wither don't style at all (there will be a designer) or use the ant design tools

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +  handleFormValues: any;
any..? rename to onSubmit

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +        style={{ margin: "15px", display: "block", textAlign: "left" }}
style..

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +            <Radio
why not use `Radio.Group` it will make many things simpler.. like having selected value
no need for `graph-type` and such

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +              fieldName="fieldOne"
you need to shoe the user different labels here, depending on the graph type

2021-02-17 09:50 UTC, alissaVrk commented on src/comps/CompanyComparison/PropertyByCategoryDropDown.tsx
> +function PropertyByCategoryDropDown(
take the one from master

2021-02-22 09:16 UTC, alissaVrk requested changes

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +  const onSelect = (fieldName: string, chosenField: string | undefined) => {
you shouldn't need to do that, the form should take care of that
please take a look at [the docs](https://ant.design/components/form/#components-form-demo-customized-form-controls)

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
>      form.current?.setFieldsValue({
why are you doing that?

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +    onSubmit(values);
switch these 2 lines. reset should be first

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
>              <PropertyByCategoryDropDown
they need different names for different types

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/PropertyByCategoryDropDown.tsx
> -      {...restProps}
we still need the rest  of the props for id and such

2021-02-22 09:16 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +  const onSubmit = (formValues: {
lets talk about it.. :)

2021-02-22 10:25 UTC, EyalMecilati commented on src/comps/CompanyComparison/CombineGraphs.tsx
> +            <div className="graphs">
for the testing

2021-02-23 16:45 UTC, alissaVrk commented on src/comps/CompanyComparison/CombineGraphs.tsx
> +            <div className="graphs">
class name is not a good attribute for tests
data-testId is the best.. then id

2021-02-28 11:21 UTC, alissaVrk approved these changes

2021-02-28 11:21 UTC, alissaVrk commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +    const findCompany = companiesId.find((company) => company.id === id);
you can store it as a map {[id]: true} then you don't need to use find

2021-02-28 11:21 UTC, alissaVrk commented on src/comps/CompanyComparison/GraphForm.tsx
> +              <Row>
you don't need Row and Col in a form.. it has the same styling properties

2021-02-28 11:23 UTC, merged