Currency and commodity selection
alissaVrk/lonely-mnt pull request #26
Opened 2021-02-24 15:08 UTC by EyalMecilati

2021-03-01 08:47 UTC, alissaVrk requested changes

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/grid/GridAll.tsx
> +  getAllCompaniesWithSelection,
there should be only one method that gets all

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/grid/GridAll.tsx
> +      <Row gutter={[0, 44]} justify="space-around">
there should be a better way to do it, not using grid for single item

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +  onCurrencyAndProductFormSubmit: (currencyAndproductObj: {
prices and all the rest should be in the same event

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +    null as { name: string; value: number }[] | null
probably will be easier with an object (map) or Record

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +          {Object.keys(ProductType).map((product) => (
there is a component for that - look at the forms

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +        <Select placeholder="Select a Currency">
same as product Type

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +            productsPricesArr ? (
you always have values here

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +                setUserProductPrices={setUserProductPrices}
onSubmitPrices..

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/utils.ts
> +  for (const [key, value] of Object.entries(productPrices)) {
1. no reason to create new object in each iteration - just set the value at the key
2. lodash has a nice method - mapValues

2021-03-01 08:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/utils.ts
> +export const getProductPricesArray = (
to be deleted

2021-03-02 15:44 UTC, alissaVrk requested changes

2021-03-02 15:44 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.test.js
> +  it("should update by user inputs and not by ratio", () => {
you need to add a test checking that you have the ratio as default

2021-03-02 15:44 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/helpers.ts
> +  if (values.productPrice !== values.productsPrices[values.productType]) {
I don't understand the `if` and you don't have tests to explain it..

2021-03-02 15:44 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductsPricesChangeForm.tsx
> +  handleProductsPricesChanged: (UserPrices: typeof productPrices) => void;
onProductPrices..

2021-03-02 15:44 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +  const onPopoverVisibleChange = () => {
not sure what this does

2021-03-04 10:17 UTC, alissaVrk requested changes

2021-03-04 10:17 UTC, alissaVrk commented on cypress/integration/app/grid.spec.js
> +        getGridValueByIndex([16,17,22],[7.33,-2.02,400],'test')//npv,irr,Estimated FCF fields
I think that you have here an array of titles, so you can find the right index by the title instead of just writing it

2021-03-04 10:17 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +    const formValue = form.current?.getFieldsValue();
why are we taking value from the form ad putting it back in the form?

2021-03-04 13:10 UTC, EyalMecilati commented on cypress/integration/app/grid.spec.js
> +        getGridValueByIndex([16,17,22],[7.33,-2.02,400],'test')//npv,irr,Estimated FCF fields
i didn't find that array

2021-03-08 09:47 UTC, alissaVrk requested changes
lets talk about it

2021-03-08 09:47 UTC, alissaVrk commented on cypress/integration/app/grid.spec.js
> +        checkGridValueByIndex([16,17,22],[7.33,-2.02,400],'test')//npv,irr,Estimated FCF fields
`titles.indexOf(col && col.title)`

look at `validateHeaderAndContentCols`function

2021-03-08 09:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductAndCurrencyEditCard.tsx
> +    if (!isEmpty(changedInput) && changedInput[0].name[0] === "productType") {
I don't understand.. what you are doing here

2021-03-08 09:47 UTC, alissaVrk commented on src/comps/productAndCurrencyEdit/ProductsPricesChangeForm.tsx
> +      [pricesObj.product]: pricesObj.productsPrices[pricesObj.product],
when do you set a single price?

2021-03-15 15:24 UTC, alissaVrk approved these changes

2021-03-15 15:28 UTC, merged