format quarter cells
alissaVrk/lonely-mnt pull request #28
Opened 2021-03-16 08:48 UTC by EyalMecilati

2021-03-16 13:29 UTC, alissaVrk requested changes

2021-03-16 13:29 UTC, alissaVrk commented on cypress/integration/app/grid.spec.js
> +    it("should show the user the right quorter and year (2022-04-01,2022-01-01)", function() {
this test should be a part of the single row - columns visibility with the rest of the non op stuff

2021-03-16 13:29 UTC, alissaVrk commented on src/logic/summery/formatValueByType.test.js
> +    forEach(dateToQuerter, (value, key) => {
you don't really need to go through all

2021-03-16 13:29 UTC, alissaVrk commented on src/utils/codeUtils.ts
> +    dateToQuerterObj = { ...dateToQuerterObj, [value]: key };
there is no need here for ...dateToQuerterObj
you can just do dateToQuerterObj[value] = key

2021-03-16 14:43 UTC, EyalMecilati commented on src/utils/codeUtils.ts
> +    dateToQuerterObj = { ...dateToQuerterObj, [value]: key };
dateToQuerterObj[value] = key is not working i added Object.assign(dateToQuerterObj, {[value]:key })

2021-03-16 14:44 UTC, alissaVrk commented on src/utils/codeUtils.ts
> +    dateToQuerterObj = { ...dateToQuerterObj, [value]: key };
it should work.., what do you mean not working?

2021-03-17 09:51 UTC, alissaVrk submitted a review, later dismissed

2021-03-17 11:46 UTC, alissaVrk approved these changes

2021-03-17 11:47 UTC, merged