add reset al prices not by ratio button,logic and test
alissaVrk/lonely-mnt pull request #34
Opened 2021-03-24 15:04 UTC by EyalMecilati

2021-03-25 13:01 UTC, alissaVrk requested changes

2021-03-25 16:10 UTC, alissaVrk requested changes

2021-03-25 16:10 UTC, alissaVrk commented on cypress/integration/app/grid/grid.spec.js
> +    it.only("should change price then reset all prices (not by ratio) and the value should not change", function(){
remove the only :)

2021-03-26 15:42 UTC, EyalMecilati commented on cypress/integration/app/grid/grid.spec.js
> +    it.only("should change price then reset all prices (not by ratio) and the value should not change", function(){
i don't see the only in the branch

2021-03-31 07:51 UTC, alissaVrk approved these changes

2021-03-31 07:51 UTC, merged