Company page
alissaVrk/lonely-mnt pull request #49
Opened 2021-04-28 13:18 UTC by EyalMecilati

2021-05-06 08:48 UTC, alissaVrk requested changes
I'm not done yet

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +          <Link to={'/company-page/'+company.id}>try me</Link>
just link the company name

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +    if( prodcut === ProductType.gold || prodcut === ProductType.silver){
it should be the same function for the grid and here
or at least use the object with the unit types per product

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +    if( prodcut === ProductType.gold || prodcut === ProductType.silver){
you don't want to have that condition in 2 places

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +export const columnsForNpvAndIrr = (npv: boolean, currency: CurrencyType | null | undefined) => {
call it isNpv if it is what it means

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +          render: (text: string) => text,
you don't need a render property if you just show it as it is

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +          render: (num: number) => `${formatNumberWithCommas(num)} (g/t)`,
it isn't always g/t - look at techSummery

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +        render: (num: number) => formatNumberWithCommas(num) + '(g/t)',
same as the grade in the other place

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +        render: (text: string) => text
no need for render, and product should be the first column

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
I'll believe you :)

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +     return [
strike price should be first

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +      <PageHeader title={`${company.name} Details`}>
company name and description should be outside of the tabs, it's always on page

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +              :"Company Don't Have Commodities"}
Doesn't

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +          <Descriptions.Item label="Company Links">
links at the bottom

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +                    <a href={link}>Go To Website</a>
show the link as the text if we don't have anything better

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +                <label>Company Dont Have Links</label>
no need for that

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +            ) : "Company Don't Have Options"}
just don't show it if there is none

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyDetails.tsx
> +          <Descriptions.Item label="Company Warrents">
just don't show it if there is none

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +    <>
?

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +              <Row>
why row inside row?

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +                  <Col offset={2} span={22} style={{ margin: "3% 0 3% 0" }}>
why do you need the margin?

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +                    {company.description ? <p>{company.description}</p> : null}
name and description out
and you already have them twice

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +                        projects={company.projects!.items as Project[]}
I think the type is ProjectFF, no?

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +                  {checkIfNotNull(project.juristiction)} - {checkIfNotNull(project.juristictionRating)} (g/t)
g/t ..?

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +                    {checkIfNotNull(project.nextMilestone)}, Quarter: {checkIfNotNull(project.nextMilestoneQuarter)}
there is a function to convert date to a quorter - look at the grid

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +                <Descriptions.Item label="Technical Commodity">
remove

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +                <Descriptions.Item label="Technical Currency">
remove

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +            : <div>Project - {project.name }, Don't Have Technical Report </div>
no need

2021-05-06 08:48 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +          : <div>Project - {project.name }, Don't Have Deposits</div>
no need

2021-05-06 10:27 UTC, EyalMecilati commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +          <Link to={'/company-page/'+company.id}>try me</Link>
insted of try me, or in the URL ?

2021-05-06 20:47 UTC, EyalMecilati commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +export const columnsForNpvAndIrr = (npv: boolean, currency: CurrencyType | null | undefined) => {
thats the columns config for the table for npv and irr. please let me know if i should change it

2021-05-06 21:53 UTC, EyalMecilati commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +          render: (num: number) => `${formatNumberWithCommas(num)} (g/t)`,
what is the symbol for PercentOfTon?

2021-05-06 21:57 UTC, EyalMecilati commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +        render: (text: string) => text
it is the first, unless i'm not understanding correctly

2021-05-06 22:09 UTC, EyalMecilati commented on src/comps/companyPage/companyPage.tsx
> +    <>
i put a div instead. why this is wrong?

2021-05-06 22:20 UTC, EyalMecilati commented on src/comps/companyPage/companyPage.tsx
> +                        projects={company.projects!.items as Project[]}
I'm not sure. I don't think so.

2021-05-09 05:58 UTC, EyalMecilati commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +          render: (num: number) => `${formatNumberWithCommas(num)} (g/t)`,
never mine

2021-05-09 08:38 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +export const columnsForNpvAndIrr = (npv: boolean, currency: CurrencyType | null | undefined) => {
I mean the parameter for the function

2021-05-09 08:38 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +    <>
why is it there at all?

2021-05-10 09:28 UTC, alissaVrk requested changes
you need at least 1 e2e test that renders all of this shit

2021-05-10 09:28 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +  const getDescriptionsItem = (
not sure I understand what's going on here

2021-05-10 09:28 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +                <Descriptions.Item label="Technical Currency">
remove :)

2021-05-18 16:06 UTC, EyalMecilati commented on src/comps/companyPage/projectsPage.tsx
> +  const getDescriptionsItem = (
if there is 2 fields include them in the same Description.Item (like jurisdiction and Jurisdiction Tier).  else check if there is 1 field if there is, return Description.Item with the field (with a formated value and title for users), else return null.

2021-05-18 16:07 UTC, EyalMecilati commented on src/comps/companyPage/companyPage.tsx
> +    <div>
it fails if i don't use it

2021-05-18 16:08 UTC, EyalMecilati commented on src/comps/companyPage/techPage.tsx
> +                  {formatNumberWithCommas(tech.opratingCost) + ` (${currency}/${ProductAmountUnits[product] === ProductUnits.OZ ? 'oz' : 'lbs'})`}
opratingCost is not an accepted value for this function

2021-05-19 14:06 UTC, alissaVrk commented on src/comps/companyPage/techPage.tsx
> +                  {formatNumberWithCommas(tech.opratingCost) + ` (${currency}/${ProductAmountUnits[product] === ProductUnits.OZ ? 'oz' : 'lbs'})`}
make a sub function getting a field type

2021-05-19 14:07 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +    <div>
never mind, next time

2021-05-19 14:11 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +  const getDescriptionsItem = (
you can make a function returning `formatValueByType(fieldsDef[fieldName], field.toString(), getCurrencyAndProduct(currency,product))` as an array and then spread
I think it would have been clearer

2021-05-19 15:57 UTC, EyalMecilati commented on src/comps/companyPage/techPage.tsx
> +                  {formatNumberWithCommas(tech.opratingCost) + ` (${currency}/${ProductAmountUnits[product] === ProductUnits.OZ ? 'oz' : 'lbs'})`}
the field is also not in the JSON file that has the user's title for the fields. can I add it to the JSON file or it will break something?

2021-05-30 09:16 UTC, alissaVrk submitted a review, later dismissed

2021-05-31 09:36 UTC, closed without merging