Refactor comparison user pref
alissaVrk/lonely-mnt pull request #52
Opened 2021-05-13 10:27 UTC by EyalMecilati

2021-05-20 11:47 UTC, alissaVrk requested changes

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
>    const onSelectAll = (checkAll: boolean) => {
I think we should remove the select/unselect all from the UI

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +  selectedCompanies: Array<string> | null | undefined;
selectedCompaniesIds

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/CompanyCheckboxList.tsx
> +       findCompany = selectedCompanies!.find((companyId) => companyId === id);
you can use some, returns boolean

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonUtils.ts
> +export const getUserPrefCompaniesAndUpdatePrefIfEmpty = (
I don't think we need this at all

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonUtils.ts
> +const getFilteredCompaniesByUserPref = (
isn't in use - delete

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonPage.tsx
> +      setSelectedCompanies(getSelectedCompaniesForComparison(filterUserPrefCompanies,selectedForComparison))
pass data instead of filterUserPrefCompanies
and this moves to const

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonUtils.ts
> +  let selectedCompanies: CompanySummery[];
it could be nice to make this prettier..
less vars - no need for both `new` and `selected`
can change to filter - not critical at all

2021-05-20 11:47 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonUtils.ts
> +      format: (x) => (x ? x.toString() : ""),
here, we can use the same format as the grid

2021-05-20 11:47 UTC, alissaVrk commented on src/logic/user-prefs/userPrefsContexts.tsx
> +  selectedForComparison: [] as UserPrefs["unSelectedCompaniesForCompareIds"],
change `unSelectedCompaniesForCompareIds` to `selectedCompanyIds`

2021-05-20 11:47 UTC, alissaVrk commented on src/logic/user-prefs/userPrefsContexts.tsx
> +  const graphsItems: { type: GraphType }[] = !isEmpty(prefs.graphsToCompare)
useMemo

2021-05-20 11:47 UTC, alissaVrk commented on src/logic/user-prefs/userPrefsContexts.tsx
> +    <UserPrefsGraphsContext.Provider value={{ graphsPrefs: graphsItems }}>
why an object you can just do `value={graphsItems}`

2021-05-20 11:47 UTC, alissaVrk commented on src/logic/user-prefs/UserPrefsReducer.test.ts
> +  describe("update graphsPrefs", () => {
add test for remove graph
and like all the rest, it could be nice to test the DB as well

2021-05-24 06:12 UTC, alissaVrk requested changes

2021-05-24 06:34 UTC, EyalMecilati commented on src/logic/user-prefs/UserPrefsReducer.ts
> +          ? state.prefs.unSelectedCompaniesForCompareIds!.filter(
changing the type seems to be problematic. on the loading stage I make unSelectedCompaniesForCompareIds to be [] and changed the ! to ?

2021-05-24 07:09 UTC, EyalMecilati commented on src/logic/user-prefs/userPrefsTypes.ts
> +  graphsToCompare?: Array< {
when I remove the null it won't fit to the prefs object in the UserPrefsReducer file.

2021-05-31 07:02 UTC, alissaVrk approved these changes

2021-05-31 07:05 UTC, merged