Add multiplier to company page
alissaVrk/lonely-mnt pull request #57
Opened 2021-06-14 11:49 UTC by EyalMecilati

2021-06-17 12:49 UTC, alissaVrk requested changes

2021-06-17 12:49 UTC, alissaVrk commented on src/comps/companyPage/companyPage.tsx
> +  const companyFF = convert(data);
it's nicer to do in the CompanyDB

2021-06-17 12:49 UTC, alissaVrk commented on src/comps/companyPage/projectsPage.tsx
> +          <DepositsSummery summery={summery} printDescriptionsItemByValue={printDescriptionsItemByValue}/>
it isn't a summery per project, it's for the whole company
don't know what Tal wanted but this is what you have in the summery

2021-06-17 16:17 UTC, EyalMecilati commented on src/comps/companyPage/projectsPage.tsx
> +          <DepositsSummery summery={summery} printDescriptionsItemByValue={printDescriptionsItemByValue}/>
he wanted to add a panel for Deposits Summery before the deposits panel

2021-06-20 08:37 UTC, alissaVrk requested changes

2021-06-20 08:37 UTC, alissaVrk commented on src/logic/companies/CompaniesDB.ts
> +import { convertToSummery } from "../summery/convertToSummery";
you can't convert to summery here...

2021-06-20 08:37 UTC, alissaVrk commented on src/logic/companies/CompaniesDB.ts
> +import { selectedProduct } from "../summery";
so is this..

2021-06-20 09:28 UTC, alissaVrk approved these changes

2021-06-20 09:30 UTC, merged