Fix values in graphs
alissaVrk/lonely-mnt pull request #64
Opened 2021-06-21 07:05 UTC by EyalMecilati

not ready

2021-06-23 14:24 UTC, alissaVrk requested changes
not done yet

2021-06-23 14:24 UTC, alissaVrk commented on cypress/fixtures/grid/titlesSymbolsObj.json
> +        "EV to Reservs":"EV to Reservs 1x",
there is no reason for the '1'..

2021-06-23 14:24 UTC, alissaVrk commented on cypress/integration/app/grid/gridColumnsVisibility.spec.js
> +        const titleWithSymbol =  titlesSymbolsObj[valueText] ? titlesSymbolsObj[valueText] : valueText;
change that name of the const, it's once a title and once a cell value..
very hard to understand

2021-06-23 14:24 UTC, alissaVrk commented on src/comps/grid/useGridColumns.tsx
> +    companiesData:{companies: CompanySummery[], productAndCurrency: ProductsPricesObj}
please pass only what you need - the product and currency

2021-06-23 14:24 UTC, alissaVrk commented on src/comps/grid/useGridColumns.tsx
> +            if(fieldName === 'nextMilestoneQuarter' || fieldName === 'targetCommercialProduction'){
please do this by type and not by name

2021-06-24 05:55 UTC, EyalMecilati commented on cypress/fixtures/grid/titlesSymbolsObj.json
> +        "EV to Reservs":"EV to Reservs 1x",
tal told me that's how he wanted it, (1 week ago)

2021-06-27 07:45 UTC, alissaVrk requested changes

2021-06-27 07:45 UTC, alissaVrk commented on cypress/fixtures/grid/singleRow.json
> +    "0.25 1x",
remove the '1', no '()' no space between the number and the 'x'

2021-06-27 07:45 UTC, alissaVrk commented on cypress/integration/app/grid/gridColumnsVisibility.spec.js
> +        const titleWithSymbol =  titlesSymbolsObj[cellOrTitle] ? titlesSymbolsObj[cellOrTitle] : cellOrTitle;
naming.. it is really hard to understand
the general case is cellContent and if applicable translate the value (symbol)

2021-06-27 07:45 UTC, alissaVrk commented on src/comps/companyPage/multiplierPage.tsx
> +          {printDescriptionsItemByValue(summery.evToFcf,'evToFcf',' 1x')}
same

2021-06-27 07:45 UTC, alissaVrk commented on src/comps/grid/useGridColumns.tsx
> +              return value && value + ' 1x'
same

2021-06-27 08:05 UTC, alissaVrk approved these changes

2021-06-27 08:07 UTC, merged