Add fix to1 only (also nit ready, other one can be deleted)
alissaVrk/lonely-mnt pull request #68
Opened 2021-06-27 10:28 UTC by EyalMecilati

2021-06-28 06:37 UTC, alissaVrk requested changes

2021-06-28 06:37 UTC, alissaVrk commented on src/comps/CompanyComparison/ComparisonUtils.ts
> +      format: (x) => formatNumberWithCommas(Number(x)) ? formatNumberWithCommas(Number(x))!.toString() : ''
it is strange to call the function twice..
why don't you just check if `x` exists?

2021-06-28 06:37 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +    let numFixed:string | number = num;
please create another var for the string

2021-06-28 06:37 UTC, alissaVrk commented on src/comps/grid/useGridColumns.tsx
> +            if (fieldDef.numberType === NumberType.Multi) {
multi !== null there is no need for 2 ifs

2021-06-28 06:37 UTC, alissaVrk commented on src/comps/grid/useGridColumns.tsx
> +            if (fieldDef.numberType != null|| fieldDef.moneyType != null) {
there is a better way to check if it's number or money, the def has a type..

2021-06-28 07:41 UTC, EyalMecilati commented on src/comps/grid/useGridColumns.tsx
> +            if (fieldDef.numberType != null|| fieldDef.moneyType != null) {
That's what I'm using, no? fieldDef.numberType and fieldDef.moneyType

2021-06-28 07:43 UTC, EyalMecilati commented on src/comps/grid/useGridColumns.tsx
> +            if (fieldDef.numberType === NumberType.Multi) {
what do you mean 2 ifs? for multi there is only one. and I can't get multi from fieldDef, I can only compare it to the fieldDef.numberType

2021-06-29 05:59 UTC, alissaVrk approved these changes

2021-06-29 05:59 UTC, alissaVrk commented on src/comps/companyPage/columnsConfigAndUtils.ts
> +      .toFixed(1)
toFixed returns string as far as I know

2021-06-30 16:25 UTC, merged