Turn negetive numbers to 0
alissaVrk/lonely-mnt pull request #69
Opened 2021-06-28 13:32 UTC by EyalMecilati

2021-06-29 06:06 UTC, alissaVrk requested changes

2021-06-29 06:06 UTC, alissaVrk commented on src/comps/graphs/graphParts.tsx
> +  const newArrWithNoNegitiveNum = []
few things:
1. there is no need to go over all the data fields only the params
2. you are copying the object each time.. it isn't good here

2021-06-29 06:06 UTC, alissaVrk commented on src/comps/graphs/graphParts.test.js
> +const objectArrAllNegetive = [
it's very nice there are tests
if the input is an array, you should have a test for more than 1 item and for empty

2021-06-29 06:06 UTC, alissaVrk commented on src/comps/graphs/useGraphData.ts
> -      data.filter((d) => params.every((param) => isNumber(d[param.field])))
we still need to filter out items with missing params

2021-06-29 06:22 UTC, EyalMecilati commented on src/comps/graphs/useGraphData.ts
> -      data.filter((d) => params.every((param) => isNumber(d[param.field])))
we are, if Im not mistaken? 
const validData = data.filter((d) => params.every((param) => isNumber(d[param.field])));
const noNegitiveNumData = getnoNegitiveNumData(validData)

2021-06-29 06:23 UTC, alissaVrk commented on src/comps/graphs/useGraphData.ts
> -      data.filter((d) => params.every((param) => isNumber(d[param.field])))
I see the first line deleted

2021-06-29 08:40 UTC, EyalMecilati commented on src/comps/graphs/useGraphData.ts
> -      data.filter((d) => params.every((param) => isNumber(d[param.field])))
its not

2021-06-30 16:24 UTC, alissaVrk requested changes

2021-06-30 16:24 UTC, alissaVrk commented on src/comps/graphs/graphParts.tsx
> +        noNnegativeNumDataObj[field] =  noNnegativeNumDataObj[field] < 0 ? 0 : noNnegativeNumDataObj[field];
you are changing the passed in company data - this is not good
might have unknown side effects

2021-06-30 16:24 UTC, alissaVrk commented on src/comps/graphs/useGraphData.ts
> +    const paramsFieldsArr = params[1] ? [params[0].field.toString(),params[1].field.toString()] : [params[0].field.toString()]
`params.map` will be easier to read I think

2021-07-04 14:58 UTC, alissaVrk submitted a review, later dismissed

2021-07-04 14:58 UTC, alissaVrk commented on src/comps/graphs/graphParts.tsx
> +        noNnegativeNumDataObj['name'] = companyData['name'];
this is should be outside of the for loop :)

2021-07-05 12:47 UTC, alissaVrk approved these changes

2021-07-05 12:47 UTC, merged